### ISSUE TITLE
Link for ptb dataset expired

### ISSUE THREAD

**Issue by saurav0530** [BiDAlab/ECGXtractor#1]
Hi,
I appreciate all your work. I was going through the codes and I encountered that some links were not opening. 
Could you please look into it?

For reference:  [Dataset link](https://dauam-my.sharepoint.com/:u:/g/personal/pietro_melzi_uam_es/Ec832XsM2HFDurbd9B2PopwBlLCtPS19J8HCwqZ5246Rng?e=cIcjZ3)

**Comment by BiDAlab** [comment]
Thank you very much. We have changed the links.

**Comment by saurav0530** [comment]
Thank you so much for reviewing my issue.


The ptb data at Physionet site ([Link](https://physionet.org/content/ptbdb/1.0.0/)) is in completely different format.
Just wanted to know, how did you preprocess the data from Physionet database to the one which you have uploaded.
I will be very thankful if you please upload the related file?

**Comment by BiDAlab** [comment]
We have updated in the folder 'other' the files that we used to convert data from Physionet in csv and preprocess them.

**Comment by saurav0530** [comment]
Hi,
Needed a help. 
Can you please share how to generate files in comparisons folder?
